#!/bin/bash

TUN_INTERFACE_NAME='tun0'
NETWORK='10.0.0.0'
IP_ADDRESS='10.0.0.1'
NETWORK_MASK='255.255.255.0'
NETWORK_ADDRESS="$IP_ADDRESS/24"

ip addr add $NETWORK_ADDRESS dev $TUN_INTERFACE_NAME
ip link set $TUN_INTERFACE_NAME up
route add -net $NETWORK netmask $NETWORK_MASK gw $IP_ADDRESS
